In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

Questions to answer
- Is there a trend with the NPS data?
    - Per track?
    - Per location?
    - Per course (2017)?
- Is there a trend with the pacing of the academy?
    - Per track?
    - Per location?
    - Per course (2017)?
- Is there information we can find regarding the schedule of what happened each week?
- Is there a consensus around each week?
    - What is the mean and std for each week, regardless of location
- Is there a relationship between NPS and pacing of academy?

Notes about 2016 Data
- Between week 4 and week 5, another column was added to see what track each person was in.
- Between week 1 and week 2, the wording in the last column was changed from tutorials to schedule

In [2]:
w1_y2016_df = pd.read_csv('datasets/NPS_2016/Anon Week 1 Feedback - LA.csv')
w1_y2016_df['Week'] = 1
w1_y2016_df

,Timestamp,How would you rate your overall satisfaction with the Summer Academy this week?,How well is the schedule paced?,Week
0,6/23/16 15:55,3,4,1
1,6/23/16 16:14,4,4,1
2,6/24/16 0:18,4,4,1
3,6/24/16 6:59,4,4,1
4,6/24/16 9:40,4,5,1
5,6/23/16 22:07,5,4,1
6,6/24/16 9:34,5,3,1

In [3]:
w2_y2016_df = pd.read_csv('datasets/NPS_2016/Anon Week 2 Feedback - LA.csv')
w2_y2016_df['Week'] = 2
w2_y2016_df

,Timestamp,How would you rate your overall satisfaction with the Summer Academy this week?,How well is the schedule paced?,Week
0,6/30/2016 14:09:14,4,2,2
1,6/30/2016 22:50:08,3,3,2
2,7/1/2016 9:34:16,4,4,2
3,7/1/2016 10:42:17,4,3,2
4,7/1/2016 11:25:53,4,3,2
5,7/1/2016 11:57:11,5,3,2
6,7/1/2016 11:58:37,5,3,2

In [4]:
w3_y2016_df = pd.read_csv('datasets/NPS_2016/Anon Week 3 Feedback - LA.csv')
w3_y2016_df['Week'] = 3
w3_y2016_df

,Timestamp,How would you rate your overall satisfaction with the Summer Academy this week?,How well is the schedule paced?,Week
0,7/8/2016 10:31:27,4,2,3
1,7/8/2016 13:45:52,4,4,3
2,7/8/2016 13:47:42,4,3,3
3,7/8/2016 13:47:59,4,3,3
4,7/8/2016 14:12:24,4,3,3
5,7/8/2016 14:13:39,5,4,3

In [5]:
w4_y2016_df = pd.read_csv('datasets/NPS_2016/Anon Week 4 Feedback - LA.csv')
w4_y2016_df['Week'] = 4
w4_y2016_df

,Timestamp,How would you rate your overall satisfaction with the Summer Academy this week?,How well is the schedule paced?,Week
0,7/15/2016 13:20:35,5,3,4
1,7/15/2016 13:22:22,5,3,4
2,7/15/2016 14:35:15,5,3,4
3,7/15/2016 15:05:10,5,4,4
4,7/15/2016 15:12:36,3,3,4
5,7/15/2016 16:59:37,4,3,4
6,7/15/2016 17:10:52,4,3,4
7,7/15/2016 19:32:26,4,3,4

In [6]:
w5_y2016_df = pd.read_csv('datasets/NPS_2016/Anon Week 5 Feedback - LA.csv')
w5_y2016_df['Week'] = 5
w5_y2016_df

,Timestamp,What track are you in?,How would you rate your overall satisfaction with the Summer Academy this week?,How well is the schedule paced?,Week
0,7/22/2016 16:15:37,Games,3,2,5
1,7/22/2016 16:16:07,Intro,4,3,5
2,7/22/2016 16:16:20,Intro,5,3,5
3,7/22/2016 16:17:04,Games,4,3,5
4,7/22/2016 16:17:09,Intro,4,3,5
5,7/22/2016 16:18:23,Games,4,3,5
6,7/22/2016 16:18:45,Intro,5,3,5
7,7/22/2016 16:19:58,Games,4,4,5
8,7/22/2016 16:20:25,Games,5,4,5
9,7/22/2016 16:20:30,Intro,5,3,5
10,7/22/2016 16:23:12,Games,4,3,5
11,7/22/2016 16:23:19,Games,4,3,5

In [7]:
w6_y2016_df = pd.read_csv('datasets/NPS_2016/Anon Week 6 Feedback - LA.csv')
w6_y2016_df['Week'] = 6
w6_y2016_df

,Timestamp,What track are you in?,How would you rate your overall satisfaction with the Summer Academy this week?,How well is the schedule paced?,Week
0,7/31/2016 8:43:57,Games,5,3,6
1,7/31/2016 11:28:09,Intro,5,3,6
2,7/31/2016 13:22:31,Games,3,1,6
3,8/1/2016 1:39:51,Games,1,3,6
4,8/1/2016 9:40:14,Intro,5,3,6
5,8/1/2016 9:40:14,Intro,5,3,6
6,8/1/2016 10:03:22,Games,5,3,6
7,8/1/2016 10:04:06,Games,4,3,6
8,8/1/2016 10:06:45,Intro,4,4,6
9,8/1/2016 11:22:56,Games,4,4,6

In [8]:
w7_y2016_df = pd.read_csv('datasets/NPS_2016/Anon Week 7 Feedback - LA.csv')
w7_y2016_df['Week'] = 7
w7_y2016_df

,Timestamp,What track are you in?,How would you rate your overall satisfaction with the Summer Academy this week?,How well is the schedule paced?,Week
0,8/5/2016 11:22:50,Intro,3,2,7
1,8/5/2016 11:23:13,Intro,5,3,7
2,8/5/2016 11:24:20,Games,4,2,7
3,8/5/2016 11:29:26,Intro,4,3,7
4,8/5/2016 11:31:08,Games,4,3,7
5,8/5/2016 11:57:53,Games,5,3,7
6,8/5/2016 13:23:30,Intro,4,4,7
7,8/5/2016 13:58:27,Games,5,3,7
8,8/5/2016 14:00:14,Games,5,3,7

In [9]:
w8_y2016_df = pd.read_csv('datasets/NPS_2016/Week 8 Feedback (2016, incomplete) - results.csv')
w8_y2016_df

,#,How likely is it that you would recommend the Make School Summer Academy to a friend?,location,track,Start Date (UTC),Submit Date (UTC),Network ID
0,00b836bda84e6bdbe780af97e249e59f,10,New York,summerApps,9/7/16 1:03,9/7/16 1:04,3212b7a834
1,39dde6dc0e1e375845d756fc7e39fc5f,10,San Francisco,summerIntro,9/7/16 1:03,9/7/16 1:04,f4954355aa
2,5e56b9de91670b308cb98dd2848b8739,10,New York,summerIntro,9/7/16 1:03,9/7/16 1:05,3d69ca289b
3,641081d05785b47a0f17448625da0d49,9,Sunnyvale,summerApps (4-week),9/7/16 1:04,9/7/16 1:06,261608f95d
4,c29bdd4f5678d78b450f4494e0f53c8c,3,San Francisco,summerIntro,9/7/16 1:04,9/7/16 1:11,d6672ddf6f
5,9030d8a662b39b519b2b685834413d66,10,San Francisco,summerApps,9/7/16 1:09,9/7/16 1:13,088e6f938d
6,1c07190c7caa72bf6b59cea48e1a4a97,8,San Francisco,summerApps,9/7/16 1:04,9/7/16 1:14,00f1d07a90
7,27a63d6c24710feb52c0cfdef7e01175,3,New York,summerGames,9/7/16 1:14,9/7/16 1:15,e0724aac23
8,b47b95f84547d8347119de1da5faa46d,6,Singapore,summerApps,9/7/16 1:16,9/7/16 1:21,9eeec0f9bf
9,828fafa477484f61d2ca5930fe99ad46,9,New York,summerGames,9/7/16 1:22,9/7/16 1:27,6c80fd2754
10,7d70f1e30217d867f3c0f961462d8ae8,10,Sunnyvale,summerGames,9/7/16 1:28,9/7/16 1:29,6c04cd1a6e
11,65bd071ab808290560e7d11c09f56796,10,San Francisco,summerVR,9/7/16 1:22,9/7/16 1:33,82eadbe830
12,d66976d012b4c8a5c708f1a438605488,8,San Francisco,summerIntro,9/7/16 1:30,9/7/16 1:36,ccea45b0f4
13,9db748a8e0d5789cb3a5fcb27fc59083,8,Sunnyvale,summerApps,9/7/16 1:47,9/7/16 1:50,9e894113e2
14,5ee2a5d8e87fd5790906f7b004963e14,8,Los Angeles,summerGames,9/7/16 1:34,9/7/16 1:51,7a61b16f29
15,9826290f1bf2fd4c105857e2af933ffe,10,San Francisco,summerApps,9/7/16 2:28,9/7/16 2:33,55641e8ccb
16,ea85e7c699751b5993776ef16db0b1d9,9,Sunnyvale,summerGames,9/7/16 2:39,9/7/16 2:41,125a8466ea
17,58cb61ce774b116d87e3888d4c1babf1,10,New York,summerGames,9/7/16 2:39,9/7/16 2:43,9f88839991
18,a08ef61cfa87d1ba00c691de4a55f4c2,7,Singapore,summerApps,9/7/16 2:47,9/7/16 2:50,bd06f31b2a
19,630fd265cdb8308b60b4b59351690f0a,10,San Francisco,summerIntro,9/7/16 2:56,9/7/16 2:56,7f24478045
20,2f7303a7ac0943b341d02678b085688e,10,San Francisco,summerApps,9/7/16 2:58,9/7/16 2:59,32fdf4fca0
21,785568c94d73aa0fad4493ee79fa3974,10,Sunnyvale,summerGames,9/7/16 2:59,9/7/16 3:01,ffbbd84b0e
22,fe02b118aea0ef15ccd06e6f7e6209f4,4,New York,summerIntro,9/7/16 3:05,9/7/16 3:08,9dbeedfbf5
23,6e2c750a71613e3fd7d5f425320cc750,9,San Francisco,summerGames,9/7/16 3:22,9/7/16 3:31,19a8645313
24,522ff7a7546272c3c98eab026e8c098a,10,Sunnyvale,summerGames,9/7/16 3:15,9/7/16 3:31,42560fe8ea
25,80fce9f8822690ad581ff8d554e6f629,9,Sunnyvale,summerApps,9/7/16 3:41,9/7/16 3:42,b194ad4477
26,e78c696358f9c59b0375884ab9217f70,10,San Francisco,summerIntro,9/7/16 4:04,9/7/16 4:05,f8ef38e4e3
27,4885e461415138a403fb0408a8060094,10,Sunnyvale,summerApps,9/7/16 4:07,9/7/16 4:10,06674df051
28,bb261d3e5b4fe2197f54f28c416948e1,7,Sunnyvale,summerGames,9/7/16 4:20,9/7/16 4:21,66eb19a8df
29,391157a49dc832edb535b3c6ee3dd6a0,10,San Francisco,summerGames,9/7/16 5:41,9/7/16 5:43,c94ee250b6
...,...,...,...,...,...,...,...
35,fa299e5db39696d38eafd4ae6e71aebb,9,Singapore,summerApps,9/7/16 12:26,9/7/16 12:26,58089eb896
36,35d559a3756563f795c0e9e81299695e,10,San Francisco,summerApps,9/7/16 12:45,9/7/16 12:48,0b7b124ce3
37,2a42f27c8a19a165f37439cfd9fed33d,10,New York,summerIntro,9/7/16 13:09,9/7/16 13:10,32c6661877
38,1e19d356f6f8eac878413ec736e46da8,9,San Francisco,summerApps (4-week),9/7/16 14:39,9/7/16 14:40,75a5cf3cee
39,a8497fc472b7a09ac6e16e658851d652,10,New York,summerApps,9/7/16 14:52,9/7/16 14:54,5a977a012b
40,3208a7393ff3fd3c67fae17c8e48db37,8,Sunnyvale,summerApps,9/7/16 15:57,9/7/16 15:58,20eafecabd
41,45d7a66a67ee79f5c9ffa6d6abb1b307,10,San Francisco,summerApps,9/7/16 17:11,9/7/16 17:21,e474841bba
42,964e2d8e91a04b8735e73aafedb54541,9,San Francisco,summerVR,9/7/16 19:13,9/7/16 19:25,ae112590e9
43,e8780f8e3d0026549c276135fd9569ef,7,New York,summerApps (4-week),9/7/16 19:23,9/7/16 19:26,a578e4964d
44,864ff3fc8e19d27f3d4c46eb4b304d35,10,San Francisco,summerApps,9/7/16 19:39,9/7/16 19:40,573a652ffb
45,c2bc67325eb91085f3686aabf309d801,10,Los Angeles,summerGames,9/7/16 19:51,9/7/16 19:57,cadcc3e368
46,fd802ce8e43aa9deade38c108298dbaf,10,Sunnyvale,summerIntro,9/7/16 23:58,9/8/16 0:00,9ba33ad0f9
47,ac671896bf86167dc073c3f52131fe70,8,New York,summerApps,9/8/16 0:50,9/8/16 0:58,1b349a7cce
48,143652af47062192767081ff1dd630cc,10,San Francisco,summerGames,9/8/16 1:55,9/8/16 1:59,94f319072c
49,f4a5aed1cad9367cc58744706de54a1b,7,Sunnyvale,summerApps,9/8/16 5:59,9/8/16 6:04,9f09067d6a
50,3c3495614eada68b5fa8e19377e1cccd,10,Los Angeles,summerGames (4-week),9/8/16 14:25,9/8/16 14:27,89b8894183
51,8e2309e3a1ba2a5630ea251b96712a9a,8,San Francisco,summerGames,9/8/16 22:00,9/8/16 22:06,01074776b4
52,44db66e47441ecd2c88dbe5dd3a38e1e,8,New York,summerApps,9/8/16 22:16,9/8/16 22:20,11c95dc87f
53,80f3d539b648cfaf92b45699e7a0545b,10,San Francisco,summerApps,9/8/16 23:06,9/8/16 23:07,0d6873c5ed
54,60343ca18c43feedab8481e25421484d,7,San Francisco,summerApps,9/8/16 23:01,9/8/16 23:11,8a13f23e89
55,5c99e0aac4efe9eecffd83e50ec7c8db,7,San Francisco,summerIntro,9/9/16 1:41,9/9/16 1:42,830f174273
56,022d99be229f86182ca1c2bc49aa2e09,10,San Francisco,summerIntro,9/9/16 4:22,9/9/16 4:25,9fc69673bd
57,5a83e1056e30a8596056bec5c050a86d,9,San Francisco,summerApps,9/9/16 11:06,9/9/16 11:09,6d5dece18c
58,50f1c0545d9cef1c10be657e1083990d,10,New York,summerGames,9/9/16 13:24,9/9/16 13:28,f7f5617754
59,22ac2ab300a76178ce53104d03408c8a,8,San Francisco,summerGames,9/10/16 22:28,9/10/16 22:30,9500d5b989
60,2d487d890a68bbdb70dd027bc1e501bb,9,San Francisco,summerApps,9/12/16 0:05,9/12/16 0:13,fe650b21f7
61,0cdf8eced1b8791ae536797c75751b25,5,San Francisco,summerVR,9/13/16 4:36,9/13/16 4:42,a7deda5bf5
62,d353c2cdff6bcf3e932579a5647d511a,10,San Francisco,summerGames (4-week),9/7/16 5:08,9/13/16 20:13,a3e21d76e3
63,f5716831fe432cef5da980038f2f8969,9,San Francisco,summerIntro,9/14/16 12:04,9/14/16 12:10,843b902fa2
64,951e9361c4da1756ae1c6fb2612cb9dd,9,Sunnyvale,summerGames,9/26/16 16:33,9/26/16 16:34,a2863e199d

In [10]:
y2017_df = pd.read_csv('datasets/NPS_2017/Student Feedback Surveys-Superview.csv')

y2017_df['Rating (Num)'] = y2017_df['Rating (Num)'].apply(pd.to_numeric, errors='coerce')
# pd.to_numeric(y2017_df['Rating (Num)'], errors='coerce')

y2017_df

,ID,Location,Track,Week,Rating (Num),Schedule Pacing
0,134,San Francisco,"Apps, Explorer",Week 1,3.0,Just right
1,36,Los Angeles,Apps,Week 1,4.0,A little too fast
2,117,San Francisco,Games,Week 1,4.0,Way too slow
3,253,NaN,NaN,Week 2,4.0,A little too fast
4,350,New York City,"Apps, Explorer",Week 1,4.0,Just right
5,23,Redwood City,Apps,Week 1,5.0,Just right
6,28,Los Angeles,Apps,Week 7,5.0,Just right
7,65,San Francisco,Apps,Week 1,5.0,A little too slow
8,101,Santa Clara,Apps,Week 1,5.0,A little too slow
9,124,Santa Clara,Apps,Week 1,5.0,Just right
10,157,Redwood City,Apps,Week 2,5.0,Just right
11,170,Oakland,Apps,Week 2,5.0,Just right
12,255,San Francisco,Apps,Week 2,5.0,Way too fast
13,289,Washington DC,Apps,Week 1,5.0,Just right
14,299,Washington DC,"Apps, Explorer",Week 1,5.0,A little too slow
15,307,NaN,NaN,Week 3,5.0,A little too slow
16,319,Redwood City,Apps,Week 3,5.0,Just right
17,336,New York City,Apps,Week 1,5.0,A little too slow
18,441,San Francisco,"Apps, Explorer",Week 3,5.0,Just right
19,482,Santa Clara,Apps,Week 3,5.0,Just right
20,37,Los Angeles,Games,Week 1,6.0,Just right
21,41,Chicago,"Apps, Explorer",Week 1,6.0,Just right
22,45,Chicago,Apps,Week 1,6.0,A little too slow
23,47,Chicago,Apps,Week 1,6.0,A little too slow
24,77,San Francisco,Apps,Week 1,6.0,A little too fast
25,78,San Francisco,Apps,Week 1,6.0,A little too fast
26,94,San Francisco,"Apps, Explorer",Week 1,6.0,Just right
27,193,Santa Clara,Apps,Week 2,6.0,Just right
28,251,San Francisco,"Apps, Explorer",Week 2,6.0,Just right
29,254,San Francisco,Apps,Week 2,6.0,Way too fast
...,...,...,...,...,...,...
1423,1470,New York City,Games,Week 7,10.0,Just right
1424,1471,New York City,Apps,Week 7,8.0,Just right
1425,1472,New York City,Games,Week 7,9.0,Just right
1426,1473,New York City,"Games, Explorer",Week 7,10.0,Just right
1427,1474,New York City,Games,Week 7,9.0,Just right
1428,1475,New York City,Apps,Week 7,9.0,Just right
1429,1476,New York City,Apps,Week 7,8.0,A little too fast
1430,1477,New York City,Games,Week 7,10.0,Just right
1431,1478,New York City,Apps,Week 7,10.0,Just right
1432,1479,New York City,Games,Week 7,9.0,Just right
1433,1480,New York City,Apps,Week 7,9.0,Just right
1434,1481,New York City,Apps,Week 7,10.0,Just right
1435,1482,New York City,Apps,Week 7,8.0,Just right
1436,1483,New York City,Apps,Week 7,7.0,A little too fast
1437,1484,New York City,"Apps, Explorer",Week 7,7.0,Way too fast
1438,1485,New York City,Apps,Week 7,7.0,Just right
1439,1486,New York City,Apps,Week 7,9.0,Just right
1440,1487,New York City,Apps,Week 7,8.0,Just right
1441,1488,New York City,"Games, Explorer",Week 7,7.0,Just right
1442,1489,New York City,"Apps, Explorer",Week 7,10.0,Just right
1443,1490,New York City,"Apps, Explorer",Week 7,10.0,Just right
1444,1491,New York City,Games,Week 7,9.0,A little too fast
1445,1492,New York City,Apps,Week 7,9.0,Just right
1446,1493,New York City,Apps,Week 7,3.0,Just right
1447,1494,New York City,"Games, Explorer",Week 7,10.0,Just right
1448,1495,New York City,"Apps, Explorer",Week 7,10.0,Just right
1449,1496,New York City,"Apps, Explorer",Week 7,8.0,Just right
1450,1497,New York City,Apps,Week 7,10.0,Just right
1451,1498,New York City,"Apps, Explorer",Week 7,1.0,A little too slow
1452,1499,New York City,Apps,Week 5,8.0,Just right

In [11]:
# TODO: Add conditional to run this once when kernal is restarted
# y2017_df['Week'] = y2017_df['Week'].str[5].astype(int)

# This code didn't work. An error about copying came up
# for index, row in y2017_df.iterrows():
#     if row['Schedule Pacing'] == 'Way too slow':
#         y2017_df.iloc[index]['Schedule Pacing'] = 1
#     if row['Schedule Pacing'] == 'A little too slow':
#         y2017_df.iloc[index]['Schedule Pacing'] = 2
#     if row['Schedule Pacing'] == 'Just right':
#         y2017_df.iloc[index]['Schedule Pacing'] = 3
#     if row['Schedule Pacing'] == 'A little too fast':
#         y2017_df.iloc[index]['Schedule Pacing'] = 4
#     if row['Schedule Pacing'] == 'Way too fast':
#         y2017_df.iloc[index]['Schedule Pacing'] = 5
# y2017_df['Schedule Pacing'] = y2017_df['Schedule Pacing'].apply(lambda x: x * 3)

pacing_types = ['None', 'Way too slow', 'A little too slow', 'Just right', 'A little too fast', 'Way too fast']
y2017_df['Schedule Pacing'] = y2017_df['Schedule Pacing'].astype("category", categories=pacing_types).cat.codes

y2017_clean_df = y2017_df[y2017_df['Rating (Num)'] > 0]

y2017_df

,ID,Location,Track,Week,Rating (Num),Schedule Pacing
0,134,San Francisco,"Apps, Explorer",1,3.0,3
1,36,Los Angeles,Apps,1,4.0,4
2,117,San Francisco,Games,1,4.0,1
3,253,NaN,NaN,2,4.0,4
4,350,New York City,"Apps, Explorer",1,4.0,3
5,23,Redwood City,Apps,1,5.0,3
6,28,Los Angeles,Apps,7,5.0,3
7,65,San Francisco,Apps,1,5.0,2
8,101,Santa Clara,Apps,1,5.0,2
9,124,Santa Clara,Apps,1,5.0,3
10,157,Redwood City,Apps,2,5.0,3
11,170,Oakland,Apps,2,5.0,3
12,255,San Francisco,Apps,2,5.0,5
13,289,Washington DC,Apps,1,5.0,3
14,299,Washington DC,"Apps, Explorer",1,5.0,2
15,307,NaN,NaN,3,5.0,2
16,319,Redwood City,Apps,3,5.0,3
17,336,New York City,Apps,1,5.0,2
18,441,San Francisco,"Apps, Explorer",3,5.0,3
19,482,Santa Clara,Apps,3,5.0,3
20,37,Los Angeles,Games,1,6.0,3
21,41,Chicago,"Apps, Explorer",1,6.0,3
22,45,Chicago,Apps,1,6.0,2
23,47,Chicago,Apps,1,6.0,2
24,77,San Francisco,Apps,1,6.0,4
25,78,San Francisco,Apps,1,6.0,4
26,94,San Francisco,"Apps, Explorer",1,6.0,3
27,193,Santa Clara,Apps,2,6.0,3
28,251,San Francisco,"Apps, Explorer",2,6.0,3
29,254,San Francisco,Apps,2,6.0,5
...,...,...,...,...,...,...
1423,1470,New York City,Games,7,10.0,3
1424,1471,New York City,Apps,7,8.0,3
1425,1472,New York City,Games,7,9.0,3
1426,1473,New York City,"Games, Explorer",7,10.0,3
1427,1474,New York City,Games,7,9.0,3
1428,1475,New York City,Apps,7,9.0,3
1429,1476,New York City,Apps,7,8.0,4
1430,1477,New York City,Games,7,10.0,3
1431,1478,New York City,Apps,7,10.0,3
1432,1479,New York City,Games,7,9.0,3
1433,1480,New York City,Apps,7,9.0,3
1434,1481,New York City,Apps,7,10.0,3
1435,1482,New York City,Apps,7,8.0,3
1436,1483,New York City,Apps,7,7.0,4
1437,1484,New York City,"Apps, Explorer",7,7.0,5
1438,1485,New York City,Apps,7,7.0,3
1439,1486,New York City,Apps,7,9.0,3
1440,1487,New York City,Apps,7,8.0,3
1441,1488,New York City,"Games, Explorer",7,7.0,3
1442,1489,New York City,"Apps, Explorer",7,10.0,3
1443,1490,New York City,"Apps, Explorer",7,10.0,3
1444,1491,New York City,Games,7,9.0,4
1445,1492,New York City,Apps,7,9.0,3
1446,1493,New York City,Apps,7,3.0,3
1447,1494,New York City,"Games, Explorer",7,10.0,3
1448,1495,New York City,"Apps, Explorer",7,10.0,3
1449,1496,New York City,"Apps, Explorer",7,8.0,3
1450,1497,New York City,Apps,7,10.0,3
1451,1498,New York City,"Apps, Explorer",7,1.0,2
1452,1499,New York City,Apps,5,8.0,3

In [17]:
promoters = y2017_clean_df[(y2017_clean_df['Rating (Num)'] >= 9)].count()['ID']
passives = y2017_clean_df[(y2017_clean_df['Rating (Num)'] >= 7) & (y2017_clean_df['Rating (Num)'] <= 8)].count()['ID']
detractors = y2017_clean_df[(y2017_clean_df['Rating (Num)'] >= 1) & (y2017_clean_df['Rating (Num)'] <= 6)].count()['ID']
NPS = (promoters - detractors) / (promoters + passives + detractors) * 100
NPS

44.267955801104975

In [12]:
for week in range(1, 8):
    print(y2017_clean_df.groupby(['Week']).get_group(week).mean())

ID                 382.621528
Week                 1.000000
Rating (Num)         8.267361
Schedule Pacing      3.114583
dtype: float64
ID                 552.712727
Week                 2.000000
Rating (Num)         8.378182
Schedule Pacing      3.229091
dtype: float64
ID                 603.834025
Week                 3.000000
Rating (Num)         8.522822
Schedule Pacing      3.153527
dtype: float64
ID                 797.326425
Week                 4.000000
Rating (Num)         8.331606
Schedule Pacing      3.134715
dtype: float64
ID                 1026.320225
Week                  5.000000
Rating (Num)          8.488764
Schedule Pacing       3.134831
dtype: float64
ID                 1226.951389
Week                  6.000000
Rating (Num)          8.541667
Schedule Pacing       3.159722
dtype: float64
ID                 1359.650000
Week                  7.000000
Rating (Num)          8.600000
Schedule Pacing       3.141667
dtype: float64

How to clean data for 2016
- Headers will be Location, Track, Week, NPS, Pacing

In [13]:
LA_frames = [w1_y2016_df, w2_y2016_df, w3_y2016_df, w4_y2016_df, w5_y2016_df, w6_y2016_df, w7_y2016_df]
LA_df = pd.concat(LA_frames)
LA_df

,How well is the schedule paced?,How would you rate your overall satisfaction with the Summer Academy this week?,Timestamp,Week,What track are you in?
0,4,3,6/23/16 15:55,1,NaN
1,4,4,6/23/16 16:14,1,NaN
2,4,4,6/24/16 0:18,1,NaN
3,4,4,6/24/16 6:59,1,NaN
4,5,4,6/24/16 9:40,1,NaN
5,4,5,6/23/16 22:07,1,NaN
6,3,5,6/24/16 9:34,1,NaN
0,2,4,6/30/2016 14:09:14,2,NaN
1,3,3,6/30/2016 22:50:08,2,NaN
2,4,4,7/1/2016 9:34:16,2,NaN
3,3,4,7/1/2016 10:42:17,2,NaN
4,3,4,7/1/2016 11:25:53,2,NaN
5,3,5,7/1/2016 11:57:11,2,NaN
6,3,5,7/1/2016 11:58:37,2,NaN
0,2,4,7/8/2016 10:31:27,3,NaN
1,4,4,7/8/2016 13:45:52,3,NaN
2,3,4,7/8/2016 13:47:42,3,NaN
3,3,4,7/8/2016 13:47:59,3,NaN
4,3,4,7/8/2016 14:12:24,3,NaN
5,4,5,7/8/2016 14:13:39,3,NaN
0,3,5,7/15/2016 13:20:35,4,NaN
1,3,5,7/15/2016 13:22:22,4,NaN
2,3,5,7/15/2016 14:35:15,4,NaN
3,4,5,7/15/2016 15:05:10,4,NaN
4,3,3,7/15/2016 15:12:36,4,NaN
5,3,4,7/15/2016 16:59:37,4,NaN
6,3,4,7/15/2016 17:10:52,4,NaN
7,3,4,7/15/2016 19:32:26,4,NaN
0,2,3,7/22/2016 16:15:37,5,Games
1,3,4,7/22/2016 16:16:07,5,Intro
2,3,5,7/22/2016 16:16:20,5,Intro
3,3,4,7/22/2016 16:17:04,5,Games
4,3,4,7/22/2016 16:17:09,5,Intro
5,3,4,7/22/2016 16:18:23,5,Games
6,3,5,7/22/2016 16:18:45,5,Intro
7,4,4,7/22/2016 16:19:58,5,Games
8,4,5,7/22/2016 16:20:25,5,Games
9,3,5,7/22/2016 16:20:30,5,Intro
10,3,4,7/22/2016 16:23:12,5,Games
11,3,4,7/22/2016 16:23:19,5,Games
0,3,5,7/31/2016 8:43:57,6,Games
1,3,5,7/31/2016 11:28:09,6,Intro
2,1,3,7/31/2016 13:22:31,6,Games
3,3,1,8/1/2016 1:39:51,6,Games
4,3,5,8/1/2016 9:40:14,6,Intro
5,3,5,8/1/2016 9:40:14,6,Intro
6,3,5,8/1/2016 10:03:22,6,Games
7,3,4,8/1/2016 10:04:06,6,Games
8,4,4,8/1/2016 10:06:45,6,Intro
9,4,4,8/1/2016 11:22:56,6,Games
0,2,3,8/5/2016 11:22:50,7,Intro
1,3,5,8/5/2016 11:23:13,7,Intro
2,2,4,8/5/2016 11:24:20,7,Games
3,3,4,8/5/2016 11:29:26,7,Intro
4,3,4,8/5/2016 11:31:08,7,Games
5,3,5,8/5/2016 11:57:53,7,Games
6,4,4,8/5/2016 13:23:30,7,Intro
7,3,5,8/5/2016 13:58:27,7,Games
8,3,5,8/5/2016 14:00:14,7,Games

In [14]:
for week in range(1, 8):
    print(LA_df.groupby(['Week']).get_group(week).mean())

How well is the schedule paced?                                                    4.000000
How would you rate your overall satisfaction with the Summer Academy this week?    4.142857
Week                                                                               1.000000
What track are you in?                                                                  NaN
dtype: float64
How well is the schedule paced?                                                    3.000000
How would you rate your overall satisfaction with the Summer Academy this week?    4.142857
Week                                                                               2.000000
What track are you in?                                                                  NaN
dtype: float64
How well is the schedule paced?                                                    3.166667
How would you rate your overall satisfaction with the Summer Academy this week?    4.166667
Week                                                                               3.000000
What track are you in?                                                                  NaN
dtype: float64
How well is the schedule paced?                                                    3.125
How would you rate your overall satisfaction with the Summer Academy this week?    4.375
Week                                                                               4.000
What track are you in?                                                               NaN
dtype: float64
How well is the schedule paced?                                                    3.083333
How would you rate your overall satisfaction with the Summer Academy this week?    4.250000
Week                                                                               5.000000
dtype: float64
How well is the schedule paced?                                                    3.0
How would you rate your overall satisfaction with the Summer Academy this week?    4.1
Week                                                                               6.0
dtype: float64
How well is the schedule paced?                                                    2.888889
How would you rate your overall satisfaction with the Summer Academy this week?    4.333333
Week                                                                               7.000000
dtype: float64

In [15]:
import glob
locations =['LA', 'NY', 'SF', 'SG', 'SV', 'HK', 'Taipei', 'Tokyo']
files = glob.glob('datasets/NPS_2016/Anon Week * Feedback - *.csv')
files
for file_name in files:
    pd.read_csv(file_name)

NameError: name 'filest' is not defined